server:
  servlet:
    context-path: /platforma/
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/basket-platform
    username: postgres
    password: qwerty123

  thymeleaf:
   cache: false
   mode: HTML
   encoding: UTF-8

  mvc:
    hidden-method:
      filter:
        enabled: true
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric
  endpoint:
    health:
      show-details: always

