server:
  servlet:
    context-path: /platforma/api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/basket_platform
    username: postgres
    password: 1111

  thymeleaf:
   cache: false
   mode: HTML
   encoding: UTF-8

